import argparse
import json
import os
import secrets
import sqlite3
from datetime import date, timedelta
from pathlib import Path

from dotenv import load_dotenv
from werkzeug.security import generate_password_hash

BASE_DIR = Path(__file__).resolve().parent
load_dotenv(BASE_DIR / ".env")

parser = argparse.ArgumentParser(description="Create a TRACE demo account and sample activity.")
parser.add_argument(
    "--database",
    default=str(BASE_DIR / "trace_demo.db"),
    help="SQLite database path (defaults to trace_demo.db, separate from trace.db).",
)
args = parser.parse_args()

database_path = Path(args.database)
if not database_path.is_absolute():
    database_path = BASE_DIR / database_path
os.environ["TRACE_DATABASE_PATH"] = str(database_path)

secret_key = os.environ.get("FLASK_SECRET_KEY", "")
if not secret_key or secret_key == "replace-with-a-long-random-secret":
    os.environ["FLASK_SECRET_KEY"] = secrets.token_urlsafe(32)

import app as trace_app  # noqa: E402

DEMO_USERNAME = "trace-demo"
DEMO_EMAIL = "trace-demo@example.invalid"


def seed_demo_data():
    with trace_app.get_db_connection() as conn:
        existing_user = conn.execute(
            "SELECT id FROM users WHERE username = ? OR email = ?",
            (DEMO_USERNAME, DEMO_EMAIL),
        ).fetchone()
        if existing_user:
            print(
                f"Demo data already exists in {database_path}. "
                "No records were changed."
            )
            return 0

        now = trace_app.current_timestamp()
        password = secrets.token_urlsafe(18)
        cursor = conn.execute(
            """
            INSERT INTO users (username, email, password_hash, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?)
            """,
            (DEMO_USERNAME, DEMO_EMAIL, generate_password_hash(password), now, now),
        )
        user_id = cursor.lastrowid

        profile = {
            "name": "TRACE Demo Learner",
            "education": "Computer Science student",
            "coding_level": "Intermediate",
            "target_role": "Software Engineer",
            "preferred_language": "Python",
            "target_company": "Example Tech",
            "goals": "Practice data structures, algorithms, and interview communication.",
            "weak_topics": ["Dynamic programming", "Graph traversal"],
        }
        conn.execute(
            """
            INSERT INTO profiles (
                user_id, name, education, coding_level, target_role,
                preferred_language, target_company, goals, weak_topics,
                profile_json, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                user_id,
                profile["name"],
                profile["education"],
                profile["coding_level"],
                profile["target_role"],
                profile["preferred_language"],
                profile["target_company"],
                profile["goals"],
                json.dumps(profile["weak_topics"]),
                json.dumps(profile),
                now,
            ),
        )

        sample_history = [
            (
                "analysis",
                "DEMO: Two Sum code analysis",
                {
                    "status": "incomplete",
                    "summary": "Sample record only; no real Gemini analysis was performed.",
                    "time_complexity": "O(n)",
                    "space_complexity": "O(n)",
                },
            ),
            (
                "interview",
                "DEMO: Interview answer feedback",
                {
                    "question": "How would you detect a cycle in a linked list?",
                    "answer": "Use two pointers moving at different speeds.",
                    "feedback": {
                        "score": 7,
                        "strengths": ["Identified the two-pointer technique"],
                        "gaps": ["Explain why the pointers meet when a cycle exists"],
                        "feedback": "Sample record only; not generated by Gemini.",
                    },
                },
            ),
            (
                "mock",
                "DEMO: Mock interview summary",
                {
                    "overall_score": 7,
                    "strengths": ["Clear problem decomposition"],
                    "areas_to_improve": ["Explain complexity consistently"],
                    "final_feedback": "Sample record only; not generated by Gemini.",
                    "practice_next": ["Review graph traversal"],
                },
            ),
            (
                "roadmap",
                "DEMO: Four-week study roadmap",
                {
                    "title": "Sample interview preparation plan",
                    "overview": "Example roadmap data, not generated for a real learner.",
                    "weeks": [
                        {
                            "week": 1,
                            "focus": "Graph traversal",
                            "goals": ["Review BFS and DFS"],
                            "practice": ["Solve one traversal problem"],
                        }
                    ],
                },
            ),
        ]
        for entry_type, title, payload in sample_history:
            conn.execute(
                """
                INSERT INTO history (user_id, entry_type, title, payload, created_at)
                VALUES (?, ?, ?, ?, ?)
                """,
                (user_id, entry_type, title, json.dumps(payload), now),
            )

        summary = {
            "overall_score": 7,
            "strengths": ["Clear problem decomposition"],
            "areas_to_improve": ["Explain complexity consistently"],
            "final_feedback": "DEMO DATA: This summary was not produced by Gemini.",
            "practice_next": ["Review graph traversal"],
        }
        conn.execute(
            """
            INSERT INTO mock_sessions (user_id, title, summary, created_at)
            VALUES (?, ?, ?, ?)
            """,
            (user_id, "DEMO: Mock interview", json.dumps(summary), now),
        )
        conn.execute(
            """
            INSERT INTO interview_plans (
                user_id, company, role, interview_date, focus_areas, roadmap, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                user_id,
                "Example Tech",
                "Software Engineer",
                (date.today() + timedelta(days=10)).isoformat(),
                json.dumps(["Dynamic programming", "Graph traversal"]),
                "DEMO DATA: Sample plan, not generated by Gemini.",
                now,
            ),
        )

    print(f"Seeded a separate demo database: {database_path}")
    print(f"Demo username: {DEMO_USERNAME}")
    print(f"One-time demo password: {password}")
    print("This is sample data, not real user activity or Gemini output.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(seed_demo_data())
    except sqlite3.IntegrityError as exc:
        raise SystemExit(f"Could not seed demo account because of a database conflict: {exc}") from exc
